feat: move truncate into main block
abak-press/sphinx-integration pull request #201
Opened 2022-04-21 06:14 UTC by Gelani-G

https://jira.railsc.ru/browse/PC4-28154

2022-04-21 06:18 UTC, isqad commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt
Не не, нужно выждать ротацию сначала, то есть после слипа

2022-04-21 06:18 UTC, isqad commented
@c1n1c

2022-04-21 06:20 UTC, Gelani-G commented
+ миграция на увеличение таймаута https://github.com/Gelani-G/pulscen/commit/169b6dd36d15424ef9849aa08edec4204144033e

2022-04-21 07:04 UTC, apress-hound commented on lib/sphinx/integration/statements/rt.rb
> +          configuration.tap { |config| config.mysql_read_timeout == default_read_timeout }
Lint/Void: Operator == used in void context.

2022-04-21 07:04 UTC, apress-hound commented on lib/sphinx/integration/statements/rt.rb
> +          configuration.tap { |config| config.mysql_read_timeout == TRUNCATE_READ_TIMEOUT }
Lint/Void: Operator == used in void context.

2022-04-21 08:01 UTC, c1n1c commented on lib/sphinx/integration/statements/rt.rb
> +          configuration.tap { |config| config.mysql_read_timeout = TRUNCATE_READ_TIMEOUT }
думаю может увеличенный таймаут для всех запросов в виппорт проще задать, т.е. вот тут - http://github.com/abak-press/sphinx-integration/blob/master/lib/sphinx/integration/statements/distributed.rb#L83, он вроде только для трункейта щас и используется

@isqad что думаешь?

2022-04-21 08:38 UTC, isqad commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt
sighup как раз только при выставленном rotate производится, то есть этот блок исполняется только при rotate

2022-04-21 08:39 UTC, isqad commented on lib/sphinx/integration/statements/rt.rb
> +          configuration.tap { |config| config.mysql_read_timeout = TRUNCATE_READ_TIMEOUT }
Да, согласен,
tap тоже не нужен, можно напрямую без tap задавать

2022-04-21 08:56 UTC, Gelani-G commented
@isqad @c1n1c осталось один баг поправить в тестах, его сделаю попозже, в остальном ок?

2022-04-21 08:56 UTC, c1n1c commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt
rotate то да, но тут и rt и не rt-индексы могут быть

2022-04-21 09:08 UTC, apress-hound commented on spec/sphinx/integration/helper_adapters/remote_spec.rb
> +          adapter.index(double('Index', core_name: 'index_name', local_options: {rotation_time: 5 * 60}, rt?: true, truncate_prev_rt: nil))
Metrics/LineLength: Line is too long. [139/120]

2022-04-21 09:08 UTC, apress-hound commented on spec/sphinx/integration/helper_adapters/remote_spec.rb
> +          adapter.index(double('Index', core_name: 'index_name', local_options: {rotation_time: 5 * 60}, rt?: true, truncate_prev_rt: nil))
Metrics/LineLength: Line is too long. [139/120]

2022-04-21 09:28 UTC, isqad commented on lib/sphinx/integration/statements/distributed.rb
> +          configuration.mysql_read_timeout = VIP_CLIENT_READ_TIMEOUT
Лучше из конфига брать, чтобы можно было поправить в проекте

2022-04-21 09:56 UTC, apress-hound commented on lib/sphinx/integration/railtie.rb
> +        vip_client_read_timeout: 15*60,
Layout/SpaceAroundOperators: Surrounding space missing for operator *.

2022-04-21 10:11 UTC, c1n1c commented on lib/sphinx/integration/statements/distributed.rb
> -          ::ThinkingSphinx::Configuration.instance.mysql_vip_client.write(query)
а давай лучше в метод создания вип-клиента это уберем, с этой синглтон-конфигурацией просто неочевидно все, пока мы заменили mysql_read_timeout и ждем выполнение запроса, потенциально могут другие клиенты успеть создаться с некорректным для них таймаутом, поэтому лучше чтобы подмена значения таймаута делалась максимально быстро, на этапе создания клиента, а уже дальше работа с этим клиентом велась как захочется

вот тут предлагаю сделать подмену - https://github.com/abak-press/sphinx-integration/blob/master/lib/sphinx/integration/extensions/thinking_sphinx/configuration.rb#L28

примерно так:
```
def with_custom_read_timeot(timeout)
  return yeild unless timeout

  old_timeout = mysql_read_timeout
  
  begin
    self.mysql_read_timeout = timeout
    yield
  ensure
    self.mysql_read_timeout = old_timeout
  end
end

def mysql_vip_client
  return @mysql_vip_client if @mysql_vip_client

  with_custom_read_timeout(Rails.application.config.sphinx_integration[:vip_client_read_timeout]) do
    @mysql_vip_client = build_mysql_client(privileged: true)
  end
end
```

в конфигурации и логичнее этот код, а метод with_custom_read_timeot нам потом в миграциях пригодится)

2022-04-21 10:56 UTC, c1n1c commented on lib/sphinx/integration/railtie.rb
> +        vip_client_read_timeout: 5,
nil)

2022-04-21 10:56 UTC, c1n1c commented
остальное ок)

2022-04-21 11:47 UTC, c1n1c approved these changes

2022-04-21 11:48 UTC, c1n1c commented
@isqad

2022-04-21 12:25 UTC, c1n1c requested changes

2022-04-21 12:25 UTC, c1n1c commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt if idx.rt?
блин, только сейчас понял, что так не прокатит - трункейт делается через команду write, которая выполняется на всех хостах (нодах), а нам тут нужно сделать трункейт только на текущем хосте

2022-04-21 12:31 UTC, isqad commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt if idx.rt?
ага,
`@ssh.within(host) {`

2022-04-21 12:42 UTC, c1n1c commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt if idx.rt?
так нам тут не ssh, а mysql нужен) а он щас так не умеет, это надо текущий хост прокидивать до клиента

2022-04-21 12:53 UTC, isqad commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt if idx.rt?
Погоди, погоди, если мы выполним транкейт только на одной ноде и будем ждать 15 минут вторую, то за 15 минут будет огромный рассинхрон, что сразу пользователи

2022-04-21 12:56 UTC, c1n1c commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt if idx.rt?
так мы трункейтим то старый же, неиспользуемый, переключение на новый перед индексацией делается - https://github.com/abak-press/sphinx-integration/blob/master/lib/sphinx/integration/helper.rb#L68

2022-04-21 13:15 UTC, isqad commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt if idx.rt?
А при чтении?

2022-04-21 13:33 UTC, c1n1c commented on lib/sphinx/integration/helper_adapters/remote.rb
> +              idx.truncate_prev_rt if idx.rt?
ну да, мы трункейт же делаем после ротации и этот рт никак уже использоваться не должен

2022-04-21 14:48 UTC, c1n1c commented on lib/sphinx/integration/extensions/thinking_sphinx/configuration.rb
> +    with_custom_read_timeout(Rails.application.config.sphinx_integration[:vip_client_read_timeout]) do
так кстати тоже не работает как вяснилось) эта зараза применяет таймаут не в момент создания клиента, а при создании конектов внутри в момент выполнения запроса, так что придется все таки переместить обертку with_custom_read_timeout там где запрос выполняется

2022-04-22 07:49 UTC, apress-hound commented on lib/sphinx/integration/extensions/thinking_sphinx/configuration.rb
> +      privileged ? vip_port : port,
Style/TrailingCommaInArguments: Avoid comma after the last parameter of a method call.

2022-04-22 08:03 UTC, Gelani-G commented
@isqad

2022-05-12 01:24 UTC, Gelani-G commented
@taleksei @isqad @c1n1c

2022-05-12 04:36 UTC, isqad approved these changes

2022-05-12 04:41 UTC, taleksei approved these changes

2022-05-12 06:15 UTC, c1n1c commented on lib/sphinx/integration/statements/distributed.rb
> +          @config ||= ::ThinkingSphinx::Configuration.instance
тут мемоизировать особо смысла нет, конфиг итак синглтон

2022-05-12 06:20 UTC, c1n1c approved these changes

2022-05-12 07:07 UTC, merged